# Generated by Django 2.0.6 on 2018-06-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('mobileNum', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNum', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('medicalConditionName', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('abbrev', models.CharField(max_length=10)),
                ('tktNum', models.CharField(max_length=200)),
                ('mobileNum', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('isOwner', models.BooleanField(default=False)),
                ('medicalConditions', models.ManyToManyField(related_name='MedicalCondition', to='Users.MedicalCondition')),
            ],
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='members',
            field=models.ManyToManyField(related_name='GroupMembers', to='Users.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='Group_members', to='Users.User'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('mobileNum', 'abbrev')},
        ),
    ]
