# Generated by Django 2.0.6 on 2018-06-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNum', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalConditionName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rideName', models.CharField(max_length=200)),
                ('minAge', models.IntegerField()),
                ('minHeight', models.FloatField()),
                ('medicalConditions', models.ManyToManyField(related_name='ride_medical_conditions', to='Users.MedicalCondition')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbrev', models.CharField(max_length=10)),
                ('tktNum', models.CharField(max_length=200)),
                ('mobileNum', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('isOwner', models.BooleanField(default=False)),
                ('medicalConditions', models.ManyToManyField(related_name='MedicalCondition', to='Users.MedicalCondition')),
                ('ridesAllowed', models.ManyToManyField(related_name='rides_allowed_for_user', to='Users.Ride')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='Group_members', to='Users.User'),
        ),
    ]
